packages:
- packages/amqp
- packages/cfworkers
- packages/cli
- packages/elysia
- packages/express
- packages/fedify
- packages/h3
- packages/hono
- packages/koa
- packages/nestjs
- packages/next
- packages/postgres
- packages/redis
- packages/sqlite
- packages/sveltekit
- packages/testing
- packages/vocab-runtime
- docs
- examples/cloudflare-workers
- examples/elysia
- examples/express
- examples/koa
- examples/next-integration
- examples/next14-app-router
- examples/next15-app-router
- examples/sveltekit-sample

catalog:
  "@cloudflare/workers-types": ^4.20250529.0
  "@fxts/core": ^1.15.0
  "@js-temporal/polyfill": ^0.5.1
  "@logtape/file": ^1.0.0
  "@logtape/logtape": ^1.0.0
  "@std/assert": "jsr:^1.0.13"
  "@std/async": "jsr:^1.0.13"
  "@std/path": "jsr:^1.0.6"
  "@sveltejs/kit": ^2.0.0
  "@types/amqplib": ^0.10.7
  "@types/express": ^4.0.0
  "@types/koa": ^2.15.0
  "@types/node": ^22.16.0
  "@nestjs/common": ^11.0.1
  amqplib: ^0.10.8
  elysia: ^1.3.8
  es-toolkit: 1.39.5
  express: ^4.0.0
  fetch-mock: ^12.5.4
  h3: ^1.15.0
  hono: ^4.0.0
  ioredis: ^5.6.1
  koa: ^2.16.0
  next: ^15.4.6
  postgres: ^3.4.7
  tsdown: ^0.12.9
  typescript: ^5.9.2
