packages:
- packages/fedify
- packages/cli
- packages/amqp
- packages/elysia
- packages/express
- packages/nestjs
- packages/h3
- packages/postgres
- packages/redis
- packages/sqlite
- packages/testing
- docs
- examples/cloudflare-workers
- examples/elysia
- examples/express
- examples/next14-app-router
- examples/next15-app-router

catalog:
  "@cloudflare/workers-types": ^4.20250529.0
  "@js-temporal/polyfill": ^0.5.1
  "@logtape/file": ^1.0.0
  "@logtape/logtape": ^1.0.0
  "@std/assert": "jsr:^1.0.13"
  "@std/async": "jsr:^1.0.13"
  "@std/path": "jsr:^1.0.6"
  "@types/amqplib": ^0.10.7
  "@types/express": ^4.0.0
  "@types/node": ^22.16.0
  "@nestjs/common": ^11.0.1
  amqplib: ^0.10.8
  elysia: ^1.3.8
  express: ^4.0.0
  h3: ^1.15.0
  ioredis: ^5.6.1
  postgres: ^3.4.7
  tsdown: ^0.12.9
  typescript: ^5.8.3
