packages:
- packages/amqp
- packages/cfworkers
- packages/cli
- packages/elysia
- packages/express
- packages/fastify
- packages/fedify
- packages/fixture
- packages/h3
- packages/hono
- packages/koa
- packages/lint
- packages/nestjs
- packages/next
- packages/postgres
- packages/redis
- packages/relay
- packages/sqlite
- packages/sveltekit
- packages/testing
- packages/vocab
- packages/vocab-runtime
- packages/vocab-tools
- packages/webfinger
- docs
- examples/cloudflare-workers
- examples/elysia
- examples/express
- examples/koa
- examples/next-integration
- examples/fastify
- examples/next14-app-router
- examples/next15-app-router
- examples/sveltekit-sample

catalog:
  "@cloudflare/workers-types": ^4.20250906.0
  "@fxts/core": ^1.20.0
  "@js-temporal/polyfill": ^0.5.1
  "@logtape/file": ^1.3.5
  "@logtape/logtape": ^1.3.5
  "@multiformats/base-x": ^4.0.1
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/core": ^2.0.0
  "@opentelemetry/sdk-trace-base": ^2.0.0
  "@std/assert": "jsr:^1.0.13"
  "@std/async": "jsr:^1.0.13"
  "@std/path": "jsr:^1.0.6"
  "@sveltejs/kit": ^2.0.0
  "@types/amqplib": ^0.10.7
  "@types/bun": ^1.2.23
  "@types/express": ^4.0.0
  "@types/koa": ^2.15.0
  "@types/node": ^22.17.0
  "@nestjs/common": ^11.0.1
  amqplib: ^0.10.9
  asn1js: ^3.0.6
  byte-encodings: ^1.0.11
  elysia: ^1.3.8
  es-toolkit: 1.43.0
  express: ^4.0.0
  fast-check: ^3.22.0
  fastify-plugin: ^5.0.1
  fastify: ^5.2.0
  fetch-mock: ^12.5.4
  h3: ^1.15.0
  hono: ^4.0.0
  ioredis: ^5.8.2
  koa: ^2.16.0
  next: ^15.4.6
  pkijs: ^3.3.3
  postgres: ^3.4.7
  tsdown: ^0.18.4
  typescript: ^5.9.3
  urlpattern-polyfill: "^10.1.0"
