name: Code refactoring
description: >-
  Propose code structure improvements without changing external behavior
labels: [ "type/refactor" ]
body:
  - type: markdown
    attributes:
      value: |
        Internal code restructuring without changing behavior.
        
        - Includes: Target area, motivation, and risk.
        - Goal: Improve maintainability or readability.

  - type: textarea
    attributes:
      label: Summary
      description: Briefly describe the change you're proposing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Target Area
      description: Which part of the codebase is affected?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: Why does this change matter? What are you trying to improve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Risk Assessment
      description: Is there any risk of regressions or unintended side effects?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Benefits
      description: What should be improved, simplified, or resolved as a result?
    validations:
      required: false
